[package]
name = "vcg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
cxx = "1.0"
[build-dependencies]
# cc = "1.0"
cc = { version = "1.0", features = ["parallel"] }
cxx-build = "1.0"